### ISSUE TITLE
Error 404 on docx files

### ISSUE THREAD

**Issue by jakic12** [ndrplz/google-drive-downloader#1]
Hello! I am trying to download a docx file with this git. The file gets downloaded, but all the file says is: Not Found
Error 404
The drive file id is 1ZzEzJbemBMPm46O2q5VcGNoPbqDu9AhhUc2djQbvbTY

**Comment by ndrplz** [comment]
Hi @jakic12 ,
that's weird, could you please report here the complete link to your shared file?

**Comment by jakic12** [comment]
https://docs.google.com/file/d/1ZzEzJbemBMPm46O2q5VcGNoPbqDu9AhhUc2djQbvbTY

**Comment by ndrplz** [comment]
Maybe I found a clue. The link you posted is not a google drive link, but a google docs one. Can you retrieve the same file through google drive instead?

**Comment by ndrplz** [comment]
I close this for lack of activity. Please let me know if you solved the issue.

**Comment by bidyutchanda** [comment]
Opening this issue again. 
This library does not seem to work on Docs file. And even by opening via Google Drive, now Drive takes us to Docs and gives a doc.google.com link.

**Comment by ndrplz** [comment]
I confirm that it does not seem to be working with Google Docs.

Also, I noticed that when you get the shareable link for Google Docs, the ID is longer than the one you get when you share another kind of file. The hashing system is different, I guess.

**Comment by aster94** [comment]
confirm it dowsn't work on google docs files. But it works on docx
