### ISSUE TITLE
zip file aren't downloading and unzipping correctly 

### ISSUE THREAD

**Issue by sadrultoaha** [ndrplz/google-drive-downloader#18]
Here is my code, and i am getting the error suddenly. While previously i have downloaded and unzipped the same file several times using this code and same file token. Why file token do not works anymore ?  
![image](https://user-images.githubusercontent.com/16709991/86516609-df7fc380-be43-11ea-85e9-bdda75bc6def.png)

Error:
Unzipping.../usr/local/lib/python3.6/dist-packages/google_drive_downloader/google_drive_downloader.py:78: UserWarning: Ignoring `unzip` since "1k4m6rjSLvFTha-E5pEHQqXOf7Gowh9mO" does not look like a valid zip file
  warnings.warn('Ignoring `unzip` since "{}" does not look like a valid zip file'.format(file_id))

**Comment by Rocky5** [comment]
It’s a google drive issue, out of my hands. It will fix itself after a few hours.

**Comment by DavideA** [comment]
Hello,

what happens if you try to download the file by browser? Any chance it is a "Disk Quota Exceeded" issue?

D

**Comment by sadrultoaha** [comment]
> Hello,
> 
> what happens if you try to download the file by browser? Any chance it is a "Disk Quota Exceeded" issue?
> 
> D

Yes, you are right. It is "Disk Quota Exceeded" issue. Thanks for your reply. I get the Disk Quota Exceeded" issue message only when trying to download the file using shared link.

**Comment by Rocky5** [comment]
Can also happen when google are having issues. But 99% of the time it’s a download quota issue.
