### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by gotexis** [ndrplz/google-drive-downloader#6]
Awesome work dude.

Could we have some sort of progress indicator for the requests?

Cheers

**Comment by ndrplz** [comment]
Sure, it's a reasonable need and that's already a pull request for something similar #5 
I'll give it a look this weekend and merge it if there are no issues!

**Comment by ndrplz** [comment]
If you use the code on the master, you should be able to set `showsize=True` to see the current progress.

**Comment by gotexis** [comment]
:smile: great job haha

**Comment by JohnGiorgi** [comment]
@ndrplz Is is possible to push the latest code to PyPI? I can see `showsize` on master but can't use it when installing from PyPI  (`pip install google-drive-downloader`).

Thanks!

**Comment by ndrplz** [comment]
@JohnGiorgi 

It should be there now! To check it out:
`pip install --upgrade googledrivedownloader`

**Comment by JohnGiorgi** [comment]
Very nice. Thanks a lot!
